version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install --force

  build:
    commands:
      #- npm run start
      - echo "Build completed successfully!"

  post_build:
    commands:
      - echo "Listing all files:"
      - find . -type f

  artifacts:
    files:
      - output/**/*
